# Generated by Django 4.0.5 on 2023-01-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testt',
        ),
    ]
