# Generated by Django 4.0.5 on 2023-01-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='salary',
            field=models.FloatField(default=0, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='currency',
            field=models.CharField(max_length=128, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Год'),
        ),
    ]
