# Generated by Django 4.0.5 on 2023-01-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tables_salary_alter_tables_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSalaryYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BYR', 'BYR'), ('RUR', 'RUR'), ('USD', 'USD'), ('EUR', 'EUR'), ('KZT', 'KZT'), ('UAH', 'UAH'), ('UZS', 'UZS')], max_length=128, verbose_name='Валюта')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('salary', models.FloatField(default=0, verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Строку',
                'verbose_name_plural': 'Динамика зарплат по годам',
            },
        ),
        migrations.DeleteModel(
            name='Tables',
        ),
        migrations.AlterModelOptions(
            name='charts',
            options={'verbose_name': 'График', 'verbose_name_plural': 'Графики динамики зарплат по годам'},
        ),
        migrations.AlterModelOptions(
            name='contentabout',
            options={'verbose_name': 'Контент', 'verbose_name_plural': 'О профессии'},
        ),
    ]
