# Generated by Django 4.0.5 on 2023-01-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tablesмacanciesyears'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TablesМacanciesYears',
            new_name='TablesVacanciesYears',
        ),
    ]
