# Generated by Django 4.0.5 on 2023-01-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_tablesмacanciesyears_tablesvacanciesyears'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableVacanciesInCityYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Город')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('salary', models.FloatField(default=0, verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Строку',
                'verbose_name_plural': 'Динамика зарплат в разных городах по годам (backend-разработчик)',
            },
        ),
        migrations.AlterModelOptions(
            name='charts',
            options={'verbose_name': 'График', 'verbose_name_plural': 'Все графики'},
        ),
        migrations.AlterModelOptions(
            name='tablesalaryyear',
            options={'verbose_name': 'Строку', 'verbose_name_plural': 'Динамика зарплат по годам (backend-разработчик)'},
        ),
        migrations.AlterModelOptions(
            name='tablesvacanciesyears',
            options={'verbose_name': 'Строку', 'verbose_name_plural': 'Динамика кол-ва вакансий по годам (backend-разработчик)'},
        ),
        migrations.AlterField(
            model_name='contentabout',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='tablesvacanciesyears',
            name='vacanсies',
            field=models.PositiveIntegerField(verbose_name='Кол-во вакансий'),
        ),
    ]
