# Generated by Django 4.0.5 on 2023-01-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_tablevacanciesincityyear_alter_charts_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSkillsInYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('title', models.CharField(max_length=256, verbose_name='Название навыка')),
                ('counter', models.PositiveIntegerField(verbose_name='Кол-во вакансий с этим навыком')),
            ],
            options={
                'verbose_name': 'Строку',
                'verbose_name_plural': 'Топ-10 навыков в году',
            },
        ),
    ]
